#!/usr/bin/env bash
# Render the "maskable" PWA icon variants into web/public/.
#
# Produces:
#   web/public/icon-192-maskable.png  (192×192, symbol at ~70% inset)
#   web/public/icon-512-maskable.png  (512×512, symbol at ~70% inset)
#
# Background fill is the app's theme color (#0b1418) so the symbol blends
# with the OS adaptive-icon container. The symbol is centered at ~70% of
# the canvas; the spec calls for a 80% safe-zone, we leave extra margin
# so aggressive masks (e.g. Pixel's superellipse) never crop the glyph.
#
# The "any" variants (icon-192.png, icon-512.png) are NOT regenerated by
# this script. They were rendered edge-to-edge by hand for #7/#21 and
# kept byte-stable so the favicon hash doesn't churn on each script run.
# If the symbol or background ever change, re-render those separately.
#
# Regenerate after editing majesty-symbol.svg or the background color:
#   bash web/scripts/render-pwa-icons.sh
#
# Requires: rsvg-convert (librsvg) + python3.
#   - Linux: apt install librsvg2-bin OR brew install librsvg
#   - macOS: brew install librsvg

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SYMBOL="$ROOT/web/scripts/majesty-symbol.svg"
OUT="$ROOT/web/public"
BG="#0b1418"
SYMBOL_COLOR="#e6edf3"

command -v rsvg-convert >/dev/null 2>&1 || {
  echo "error: rsvg-convert not found. Install librsvg." >&2
  exit 1
}
command -v python3 >/dev/null 2>&1 || {
  echo "error: python3 not found." >&2
  exit 1
}

[[ -f "$SYMBOL" ]] || { echo "error: $SYMBOL not found" >&2; exit 1; }

# Extract the <path d="..."/> element from the symbol SVG.
PATH_XML=$(grep -oE '<path[^/]*/>' "$SYMBOL" | head -1)
[[ -n "$PATH_XML" ]] || { echo "error: no <path/> found in $SYMBOL" >&2; exit 1; }

render_maskable() {
  local size="$1" output="$2"
  local inset_pct="0.70"  # symbol fills 70% of canvas, centered
  local canvas=1024       # render at high res then downscale

  # Compose a square SVG: background rect + the majesty path scaled and
  # centered. The symbol's viewBox is "164 109 281 249" (sym_w=281, sym_h=249).
  python3 - "$canvas" "$inset_pct" "$BG" "$SYMBOL_COLOR" "$PATH_XML" <<'PY' > /tmp/pwa-icon-wrapper.svg
import sys
canvas = int(sys.argv[1])
inset = float(sys.argv[2])
bg = sys.argv[3]
fg = sys.argv[4]
path_xml = sys.argv[5]

# Symbol viewBox: 164 109 281 249
sym_x, sym_y = 164, 109
sym_w, sym_h = 281, 249
inset_box = canvas * inset
scale = inset_box / max(sym_w, sym_h)
draw_w = sym_w * scale
draw_h = sym_h * scale
x = (canvas - draw_w) / 2 - sym_x * scale
y = (canvas - draw_h) / 2 - sym_y * scale

print(f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{canvas}" height="{canvas}" viewBox="0 0 {canvas} {canvas}">
  <rect width="{canvas}" height="{canvas}" fill="{bg}"/>
  <g transform="translate({x:.4f} {y:.4f}) scale({scale:.6f})" fill="{fg}">
    {path_xml}
  </g>
</svg>''')
PY
  rsvg-convert --width="$size" --height="$size" /tmp/pwa-icon-wrapper.svg -o "$output"
  echo "rendered: $output ($size×$size, symbol inset=$(printf %.0f $(echo "$inset_pct * 100" | bc))%)"
}

render_maskable 192 "$OUT/icon-192-maskable.png"
render_maskable 512 "$OUT/icon-512-maskable.png"

rm -f /tmp/pwa-icon-wrapper.svg
echo "done."
